FROM docker.io/openjdk:11.0.2-jre-slim-stretch

ARG CONFIG_SERVER_URI_ARG
ARG SPRING_PROFILES_ARG

RUN apt-get update && apt-get -y install procps && apt-get -y install vim

ADD target/financial-exchange-trades-0.0.1-SNAPSHOT.jar /

ENV config_server_uri $CONFIG_SERVER_URI_ARG
ENV spring_profiles $SPRING_PROFILES_ARG

EXPOSE 8080/tcp 8084/tcp

WORKDIR /
ENTRYPOINT cd / && java -jar ./financial-exchange-trades-0.0.1-SNAPSHOT.jar

